# This workflow will build a package using Maven and then publish it to maven snapshots
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package Snapshot

on:
  push:
    tags:
      - 'v*' # Push events to matching v*
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Maven
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Import GPG Key
      uses: crazy-max/ghaction-import-gpg@v4
      with:
          gpg_private_key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true
          git_push_gpgsign: false
